### ISSUE TITLE
Telemetry should include a license ID

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1641] opened 2023-02-01 13:15 UTC
### Description

To identify a license back to a customer based on a telemetry ping we should include some form of an ID. This could be the SHA256 of the blob, or anything else that uniquely identifies a license. The ID should be known at the time of generation.

### Epic/Story

https://github.com/flowforge/flowforge/issues/1638

**Comment by knolleary** [comment] 2023-02-01 13:27
Duplicate of #1607

**Closed** 2023-02-16 10:17 UTC
Labels: task
