### ISSUE TITLE
504 Gateway Timeout when opening editor: { "error": { "code": "unexpected_error", "message": "Error: connect ETIMEDOUT 178.X.X.X:443" } }

### ISSUE THREAD

**Issue by AMWN** [flowforge/flowforge#1496] opened 2022-12-30 22:26 UTC
### Current Behavior

When opening the editor from my first created project it won't load the editor and after 2 minutes show 504 Gateway Timeout. Browser is redirecting to https://forge-01.example.com/auth/strategy/callback?code=ZdaiFP8OLKMW_XJnORTDpEUYviEf__gN9eBotknYF-g&state=ZNiXg8QOBEdW7Q7VerGyguIh

When look in the log of the project I see this error:
`Error: auth.login.fail.oauth
{ "error": { "code": "unexpected_error", "message": "Error: connect ETIMEDOUT 178.X.X.X:443" } }`

### Expected Behavior

I expect the browser to show the editor of my first created project.

### Steps To Reproduce

Followed the docker install documentation. After that forge docker didn't start because of the error `ERROR: Failed to start: SequelizeConnectionError: database "flowforge" does not exist`. Fixed this by manually run setup-db.sh from within the postgres docker. After that the forge docker starts. Weird but seems ok now.

After that I did the first run steps and created a project. After a while the project is running.
When navigating to the editor, I got this error...  

### Environment

Fresh install of Ubuntu VPS. 
- FlowForge version: 1.2.0
- Node.js version: 16.19
- Platform/OS: Ubuntu 22.04.1
- Browser: Chrome

**Comment by hardillb** [comment] 2022-12-30 22:29
Please supply your `etc/flowforge.yml` file and details of how you setup DNS

**Comment by hardillb** [comment] 2022-12-30 22:36
Also include the `docker-compose.yml` so we can see what modifications you have made.

And which method have you used to setup up HTTPS?

**Comment by AMWN** [comment] 2022-12-30 22:45
**DNS**
I registered a new domain, lets say flinexample.nl. 
Created a DNS-record for *.flinexample.nl to the ip-adres of my server.

[docker-compose.txt](https://github.com/flowforge/flowforge/files/10326463/docker-compose.txt)
[flowforge.txt](https://github.com/flowforge/flowforge/files/10326464/flowforge.txt)

**Comment by AMWN** [comment] 2022-12-30 22:56
For whats its worth; I used the zip-file instead of the tar.gz from the releases...

**Comment by hardillb** [comment] 2022-12-30 23:38
Just double checking when you say the project logs, you mean under the logs tab in the forge web app?

Also ETIMEOUT error is pointing to the public IP address of the VPS? (178.x.x.x)

And `forge-01` is the name of the project?

I know why the DB setup failed first time, I have opened a PR to fix that, I'll try and get it merged when everybody is back at work early next week.

Testing locally without HTTPS I can't reproduce this just yet, so I will spin up a public facing machine in the morning so I can enable LetsEncrypt and give it another go.

Just out of interest which hosting provider are you using?

Looking at the error it implies that the container running the project has timed out trying to connect to the forge app on it's public DNS name, which is not something I would expect, since it all should be local to the host machine (after the DNS lookup which given the IP address is in the error appears to have happened correctly)

**Comment by AMWN** [comment] 2022-12-31 10:17
> Just double checking when you say the project logs, you mean under the logs tab in the forge web app?
> 
No. Under the activity tab

> Also ETIMEOUT error is pointing to the public IP address of the VPS? (178.x.x.x)
> 
Yes

> And `forge-01` is the name of the project?
> 
Yes

> I know why the DB setup failed first time, I have opened a PR to fix that, I'll try and get it merged when everybody is back at work early next week.
> 
Perfect

> Testing locally without HTTPS I can't reproduce this just yet, so I will spin up a public facing machine in the morning so I can enable LetsEncrypt and give it another go.
> 
> Just out of interest which hosting provider are you using?
> 
Digital Ocean

> Looking at the error it implies that the container running the project has timed out trying to connect to the forge app on it's public DNS name, which is not something I would expect, since it all should be local to the host machine (after the DNS lookup which given the IP address is in the error appears to have happened correctly)

**Comment by hardillb** [comment] 2022-12-31 11:08
One last question, how did you install docker on Ubuntu 22.04?

- apt install docker.io
- snap install docker

Thanks

**Comment by AMWN** [comment] 2022-12-31 11:26
> One last question, how did you install docker on Ubuntu 22.04?
> 
> * apt install docker.io
> * snap install docker
> 
> Thanks

Took the ubuntu docker image from digital ocean marketplace. Docker was pre installed.

**Comment by hardillb** [comment] 2022-12-31 11:53
OK, I've reproduced this.

Will double check it with installing docker manually to see if it's something in the Digital Ocean Docker Droplet image.

**Comment by hardillb** [comment] 2022-12-31 12:01
First findings:

- curl from inside the project container can resolve, but not connect to the host public IP address
- curl can connect to the internal forge app (http://forge:3000)
- curl can connect to other external site (e.g. https://www.hardill.me.uk)

This makes me think it's a local firewall, hairpin NAT problem on the Digital Ocean Docker image so far.

**Comment by hardillb** [comment] 2022-12-31 12:04
First findings:

- curl from inside the project container can resolve, but not connect to the host public IP address
- curl can connect to the internal forge app (http://forge:3000)
- curl can connect to other external site (e.g. https://www.hardill.me.uk)

This makes me think it's a local firewall, hairpin NAT problem on the Digital Ocean Docker image so far.

**Comment by hardillb** [comment] 2022-12-31 12:11
Yep, looks to be a ufw problem

Please run the following commands as root:

```
ufw allow http
ufw allow https
```

This should fix the problem.

I will open an issue to add a comment to the docs.

**Comment by AMWN** [comment] 2022-12-31 12:45
Yes, this is it. Thank you. 
What I don't understand is that I could reach flowforge, which is also on port 443. 
Nginx is reverse proxying to local node-red docker instance, isn't it?

**Comment by hardillb** [comment] 2022-12-31 12:48
Yes, the fact that external http/https requests were working is very strange, I assume it's because Docker inserts the mapped ports at the forwarding stage, but traffic from the docker internal network must not hit the same tables.

I'm going to close this issue now as we have solved your problem and will get the docs updated to mention this problem (again probably on Tuesday when the rest of the team are back in to review the PRs)

**Closed by hardillb** 2022-12-31 12:48 UTC
Labels: needs-triage
