### ISSUE TITLE
Project link node cannot pass msg.res and msg.req through

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2095] opened 2023-05-05 10:48 UTC
### Current Behavior

When sending msg.res and msg.req as created by the HTTP in mode to the project link node the project link node fails, it shows the following error.

TypeError: Cannot read properties of undefined (reading 'name')

### Expected Behavior

All msg content should be passed through the project link node.

### Steps To Reproduce

Create an API using HTTP in , link the wire to a project link node.

```
[{"id":"d9de4080a64b04ec","type":"http in","z":"925b1497478aadf9","name":"","url":"/example","method":"get","upload":false,"swaggerDoc":"","x":250,"y":1020,"wires":[["4539eb1c9ea78e95"]]},{"id":"4539eb1c9ea78e95","type":"project link call","z":"925b1497478aadf9","name":"","project":"fb14b545-136a-4e56-91e9-ae51efef4dcb","topic":"example","timeout":"30","x":400,"y":1020,"wires":[["2c7e5ce7e459575e"]]},{"id":"2c7e5ce7e459575e","type":"http response","z":"925b1497478aadf9","name":"","statusCode":"","headers":{},"x":530,"y":1020,"wires":[]},{"id":"5bbfb6ae79902371","type":"project link in","z":"925b1497478aadf9","name":"project in 3","project":"all","broadcast":false,"topic":"example","x":300,"y":1100,"wires":[["62deca74ea55f89a"]]},{"id":"62deca74ea55f89a","type":"project link out","z":"925b1497478aadf9","name":"project out 3","mode":"link","broadcast":false,"project":"fb14b545-136a-4e56-91e9-ae51efef4dcb","topic":"example","x":450,"y":1100,"wires":[]}]
```

I found a work around for now by passing the res and req around the project link then using an automatic join. It's not pretty but it seems to work.

```
[{"id":"d9de4080a64b04ec","type":"http in","z":"925b1497478aadf9","name":"","url":"/example","method":"get","upload":false,"swaggerDoc":"","x":90,"y":1020,"wires":[["e3047958ca31198a","1203d5720d8c8338"]]},{"id":"4539eb1c9ea78e95","type":"project link call","z":"925b1497478aadf9","name":"","project":"fb14b545-136a-4e56-91e9-ae51efef4dcb","topic":"example","timeout":"30","x":560,"y":1020,"wires":[["30175448c665bec8"]]},{"id":"2c7e5ce7e459575e","type":"http response","z":"925b1497478aadf9","name":"","statusCode":"200","headers":{},"x":1580,"y":1020,"wires":[]},{"id":"5bbfb6ae79902371","type":"project link in","z":"925b1497478aadf9","name":"project in 3","project":"all","broadcast":false,"topic":"example","x":480,"y":1100,"wires":[["4d824d55006986aa"]]},{"id":"62deca74ea55f89a","type":"project link out","z":"925b1497478aadf9","name":"project out 3","mode":"return","broadcast":false,"project":"fb14b545-136a-4e56-91e9-ae51efef4dcb","topic":"example","x":810,"y":1100,"wires":[]},{"id":"e3047958ca31198a","type":"change","z":"925b1497478aadf9","name":"remove res and req from payload","rules":[{"t":"delete","p":"res","pt":"msg"},{"t":"delete","p":"req","pt":"msg"},{"t":"set","p":"parts.id","pt":"msg","to":"_msgid","tot":"msg"},{"t":"set","p":"parts.count","pt":"msg","to":"2","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":320,"y":1020,"wires":[["4539eb1c9ea78e95"]]},{"id":"1203d5720d8c8338","type":"change","z":"925b1497478aadf9","name":"This path sends the API res and req around the project link node","rules":[{"t":"set","p":"parts.id","pt":"msg","to":"_msgid","tot":"msg"},{"t":"set","p":"parts.count","pt":"msg","to":"2","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":980,"wires":[["30175448c665bec8"]]},{"id":"30175448c665bec8","type":"join","z":"925b1497478aadf9","name":"Join the res and req back to the msg from the project link node","mode":"auto","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":true,"timeout":"","count":"","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":890,"y":1020,"wires":[["e42aa08f11885447","ec919d3506e120bb"]]},{"id":"4d824d55006986aa","type":"change","z":"925b1497478aadf9","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"Reply","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":640,"y":1100,"wires":[["62deca74ea55f89a","e5bd4fbc2d398fec"]]},{"id":"e42aa08f11885447","type":"debug","z":"925b1497478aadf9","name":"debug 79","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1220,"y":1060,"wires":[]},{"id":"ec919d3506e120bb","type":"change","z":"925b1497478aadf9","name":"Set the payload back to be a single object","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload[1]","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1320,"y":1020,"wires":[["2c7e5ce7e459575e","798ddb47fd280f24"]]},{"id":"798ddb47fd280f24","type":"debug","z":"925b1497478aadf9","name":"debug 81","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1580,"y":1060,"wires":[]},{"id":"e5bd4fbc2d398fec","type":"debug","z":"925b1497478aadf9","name":"debug 82","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":800,"y":1160,"wires":[]}]
```

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by robmarcer** [comment] 2023-05-05 10:51
@hardillb please add any details I've missed.

**Comment by hardillb** [comment] 2023-05-05 10:55
The root cause is that the node is trying to serialise the whole `msg` object to JSON to publish to the remote "instance".

We know the `msg.req` and `msg.res` objects contain circular references and links to functions and native structures that can not be serialised.

There is absolutely nothing in the `msg.res` shouldn't have anything in it that is useful to the remote instance, and there is limited useful bits in `msg.req` (e.g. query params, and URL path) that might be useful.

I think we should add a special case to the node to remove these values if both are present, stash them, serialise the rest of the `msg` object and then re-attach them to the returned object before passing on.

At the very least  we need to document this edge case and the workaround

**Comment by hardillb** [comment] 2023-09-18 13:26
@Steve-Mcl Didn't you fix this for the guy on the Node-RED Slack recently?

**Comment by Steve-Mcl** [comment] 2023-09-18 13:51
@hardillb Yes, fixed and (IIRC) made it into the latest release too.

**Comment by Steve-Mcl** [comment] 2023-09-18 13:54
Issue: https://github.com/flowforge/flowforge-nr-project-nodes/issues/42
PR: https://github.com/flowforge/flowforge-nr-project-nodes/pull/43

@robmarcer does this satisfy this issue? please feedback and/or close the issue as you see fit.

**Comment by Steve-Mcl** [comment] 2023-09-18 13:55
(I hadnt spotted this issue due to being in the main repo instead of the project-nodes repo)

**Comment by Steve-Mcl** [comment] 2023-09-21 10:32
@robmarcer I am closing this - please re-open if required.

**Closed by Steve-Mcl** 2023-09-21 10:32 UTC
Labels: bug, size:S - 2

**Comment by robmarcer** [comment] 2023-09-21 11:52
Thanks @Steve-Mcl, looks good to me.
