### ISSUE TITLE
Allow stacks to have a nice name

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#1011] opened 2022-09-22 18:59 UTC
### Description

When picking a stack the text doesn't include any spaces. This makes the text in the pill to click awkward to parse.

Maybe stacks should have a internal name, and external one? One friendly to be used when there's user facing interactions.

**Comment by ZJvandeWeg** [comment] 2022-09-22 19:00
Example: 
![Screenshot 2022-09-22 at 21 00 05](https://user-images.githubusercontent.com/2529595/191829823-0f5efcfa-6bbb-4fd5-898f-bf38f79778f9.png)

**Comment by knolleary** [comment] 2022-09-22 19:23
Duplicate of https://github.com/flowforge/flowforge/issues/915 that's in the 1.0 plan.

**Closed by knolleary** 2022-09-22 19:23 UTC
Labels: feature-request, needs-triage
