### ISSUE TITLE
Login button is not centered

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#465] opened 2022-04-08 10:26 UTC
### Current Behavior

Login button is off-centre in current `main`

<img width="346" alt="Home_-_FlowForge" src="https://user-images.githubusercontent.com/51083/162417189-8eadaebe-ce3f-4471-af42-e7784be414df.png">

### Expected Behavior

Login button is centered like it is in 0.3 (this screenshot from app.flowforge.com)

<img width="407" alt="image" src="https://user-images.githubusercontent.com/51083/162417406-55f5aba8-27ba-47cb-8979-624f9d62b280.png">

### Environment

- FlowForge version: latest code in git

**Comment by joepavitt** [comment] 2022-04-12 09:14
<img width="308" alt="Screenshot 2022-04-12 at 10 14 08" src="https://user-images.githubusercontent.com/99246719/162925459-c4b7a541-76c7-4ee2-ac78-c2fce42e2a4e.png">

cannot reproduce, screenshot from `main` in Chrome.

**Comment by sammachin** [comment] 2022-04-14 15:11
Checked 0.4 release as deployed to Staging and cannot reproduce so closing.

**Closed by sammachin** 2022-04-14 15:11 UTC
Labels: bug, frontend
