### ISSUE TITLE
Node-RED logs broken for an HA instance

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#2303] opened 2023-06-16 10:13 UTC
### Description

While I understand why this doesn't work, right now it shows the loading animation and a toaster after a few seconds that an HTTP request failed.

The user doesn't understand what HTTP has to do with it I think, or might not understand why it doesn't work.

Potential fixes:
1. Remove the tab on the left handside
2. Explain with an empty state why it doesn't work
3. Allow logs for each instance
4. Merge logs for all instances

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment] 2023-06-16 10:27
Logging works just fine for HA instances, it just interleaves both sets of logs (with no indication as to which is which).

I suspect this error is to do with both instances not being running yet. but with what is here it's not possible to say more.

**Comment by knolleary** [comment] 2023-06-16 10:44
See also https://github.com/flowforge/flowforge/issues/1083 - which is planned for the current iteration

**Comment by MarianRaphael** [comment] 2023-06-28 11:21
I'll close this issue. With the implementation of https://github.com/flowforge/flowforge/issues/1083, the problem is solved. We will further improve the HA logs in https://github.com/flowforge/flowforge/issues/2260.

**Closed by MarianRaphael** 2023-06-28 11:21 UTC
Labels: bug, task
