### ISSUE TITLE
Node-Red instance creation not increasing port causing conflicts

### ISSUE THREAD

**Issue by concept10** [flowforge/flowforge#231] opened 2022-01-24 17:29 UTC
### Current Behavior

After initial installation and test of the FlowForge platform application (git clone workflow), creating admin user, team, and project(s), the first node-red instance uses port 7880, and subsequent instances all are created and use port 7881.  When attempting to start/stop/restart, all instances using port 7881 are stopped or attempting to restart (due to port conflict?)
![Screenshot from 2022-01-24 11-16-29](https://user-images.githubusercontent.com/536986/150833871-e2caebe4-7b92-4249-82a0-153f9aabef09.png)

### Expected Behavior

Increase the port number of instances created

### Environment

- FlowForge version: 0.1.1
- Node.js version: v14.18.3
- npm version: 8.3.1
- Platform/OS: PRETTY_NAME="Ubuntu 21.10" (desktop)
- Browser: Firefox 96.0.2 (64-bit)

**Comment by hardillb** [comment] 2022-01-24 18:20
I can't reproduce this on my end. But FlowForge required NodeJS 16 (there is PR #228 to enforce this waiting to be merged.

Please try again with NodeJS 16.

You will need to delete the projects with duplicate port numbers as they allocated at creation time.

**Comment by concept10** [comment] 2022-01-25 20:41
Thanks for the follow up.  I'll reinstall on node 16 lts for testing, today.

**Comment by hardillb** [comment] 2022-02-15 09:54
@concept10 how did this go? Would like to close this out before the next release. Thanks

**Comment by hardillb** [comment] 2022-03-23 11:16
Closing this as I believe it was #333 and fixed by https://github.com/flowforge/flowforge-driver-localfs/pull/32

**Closed by hardillb** 2022-03-23 11:16 UTC
Labels: needs-triage
