### ISSUE TITLE
Export to External Node-RED

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#422] opened 2022-03-28 13:08 UTC
### Epic

#268

### Description

**As a:** Flow developer

**I want to:** Have my edge/remote Node-RED updated with cloud developed flows

**So that:** The update happens to edge devices

### Acceptance Criteria

- [ ] remote Node-RED can be registered to a project
- [ ] remote Node-RED automatically updates when new flows are developed

**Comment by sammachin** [comment] 2022-03-29 08:45
duplicate of #272

**Closed by sammachin** 2022-03-29 08:45 UTC
Labels: story
