### ISSUE TITLE
Redirect to original destination if login required

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge#973] opened 2022-09-13 09:29 UTC
### Description

**As a:** user

**I want to:** be taken to the page I was trying to reach after logging in

**So that:** I don't end up back on the default 'home' page

---

Currently, if a user is not logged in when they try to access the platform they are taken to the login page. After logging in, they are shown their default team page.

It would be better if they had followed a link to a particular page (for example, a project page, or the list of pending invitations), that they get delivered to that page after logging in.

See #954 for an example use case for this.

### Which customers would this be availble to

All Users, (CE)

### Acceptance Criteria

- [ ] try to access a project page without being logged in. Log in - see you are redirected to that project page.

**Comment by sammachin** [comment] 2022-09-13 11:44
duplicate of #974

**Closed by sammachin** 2022-09-13 11:44 UTC
Labels: story
