### ISSUE TITLE
Device logs not showing when expected in FlowForge

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2074] opened 2023-05-02 15:19 UTC
### Current Behavior

When my instance of Node-RED managed by the device agent sends information to the Node-RED log it is not showing in the device logs page in FlowForge.

### Expected Behavior

I should see the logged data for the device in the relevant page of FlowForge.

### Steps To Reproduce

1. Run an instance of NR using the Device Agent.
2. Create some logged items.
3. Check they are seen on the device's command line.
4. Check for the same log items in FlowForge.

This 5 minute video shows exactly what I tested - https://d.pr/v/uyTWBg

### Environment

- FlowForge version: 1.6
- Node.js version: v18.15.0
- npm version: 9.5.0
- Platform/OS: Mac current
- Browser: Chrome current

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by robmarcer** [comment] 2023-05-02 15:25
It just occurred to me, I can test this outside of running the device agent via systemctl so I tired that, didn't seem to change anything.

I just noticed that the logs seems to show fine until I send some data to the log from the debug node. As soon as I send one of those the debug vanishes from the screen. 

Video of this outcome - https://d.pr/v/F6kZpd

**Comment by knolleary** [comment] 2023-05-02 15:30
@robmarcer is this a self-hosted FF instance or running against staging/production?

**Comment by robmarcer** [comment] 2023-05-02 15:37
If I only send 'hello logs' to the log it does not fail - https://d.pr/i/Ha1xlD

**Comment by hardillb** [comment] 2023-05-02 15:52
I think this is to do with `NaN` not being valid JSON

**Comment by hardillb** [comment] 2023-05-03 08:56
@robmarcer What version of the device agent are you using for this test?

**Comment by robmarcer** [comment] 2023-05-03 09:12
@hardillb it's 0.7.0 - https://d.pr/i/xeJ2Ij

**Comment by hardillb** [comment] 2023-05-03 09:49
OK, working with Rob have worked out that the correct messages appear to be making it all the way to the browser and it's the rendering in page that is the problem, not the device agent or the forge app.

**Comment by hardillb** [comment] 2023-05-03 11:50
OK, I have a local reproduce and a fix, will link PRs in a moment

**Comment by hardillb** [comment] 2023-05-03 12:10
The problem was that one something was publishing a JSON object as the first argument to `node.error()` and logging assumed all messages would be strings. I have done a 2 stage fix:

1. Fix the device agent to stringify any objects before sending https://github.com/flowforge/flowforge-device-agent/pull/80
2. Fix the FlowForge device log page to check for objects and stringify them again, this is to ensure that device agent 0.7.0 will always work as expected. https://github.com/flowforge/flowforge/pull/2079

Do we want to back port #2079 and ship?

**Comment by knolleary** [comment] 2023-05-05 16:28
With both PRs merged, closing the issue and moving to verify.

**Closed by knolleary** 2023-05-05 16:28 UTC
Labels: bug, size:S - 2, priority:high, area:device
