### ISSUE TITLE
Device continues to run edited flows once taken out of dev mode

### ISSUE THREAD

**Issue by robmarcer** [flowforge/flowforge#2323] opened 2023-06-21 19:10 UTC
### Current Behavior

Edits made to flows on a device which is in dev mode are not rolled back when device is taken out of dev mode.

### Expected Behavior

Any edits made to flows on a device when it is in dev mode should be replaced with the target snapshot once the device is no longer in dev mode.

### Steps To Reproduce

1. Put a device in to dev mode and enable editor access
2. Edit the flow on that device
3. Create a snapshot but DO NOT set as target
4. Disable dev mode on that device
5. The edited flow is still running on that device

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment] 2023-06-22 09:50
There are a couple parts to this.

Currently the device is not proactively told when its mode is changed. It relies on the periodic call home to discover that its mode has changed. Strictly speaking, that doesn't need to change, but it does cause a perception that nothing is happening when the device mode changes on the platform. It would be far better for the device to log promptly when its mode has changed.

The second part is then what should happen when the device leaves developer mode.

The dialog the user is shown says this:

> Disabling developer mode will turn off access to the editor and deploy the current target snapshot to the device.
> Any changes made to the device whilst in developer mode will be lost.
> To save changes, use the 'create snapshot' developer mode option before disabling developer mode.

That is pretty clear that the expected behaviour is for the device to revert to the current snapshot.

Now, it is possible that because of the first point, the perception is that the device hasn't reverted... but if it waits long enough (for the next call home to happen) that it will then revert at that point. We need to confirm exactly what is happening.

**Comment by hardillb** [comment] 2023-06-26 13:26
Do we have a meaningful way to know if the flow was changed while in developer mode? We don't include checksums or time stamps in what gets pushed to the device.

So we need a way to know to download the snapshot again and apply it.

**Comment by Steve-Mcl** [comment] 2023-06-26 13:38
Agreed actions
1. improve logging (into/out-of dev mode, enable/disable of tunnel)
2. Part of the above, also, improve the switching operation: On top of the existing "poll for mode/state", push the instruct to the device via mqtt - therefore the action and mode change (and the log event) will be in quick succession & reduce confusion.
   * !important to check how this behaves when operated against an over agent! - **might** be possible to be selective on which devices this event is sent to (by version number check?)
3. In line with what @hardillb has stated, some kind of checksum will be required otherwise in the event of no changes, the same snapshot would be re-applied.

**Closed** 2023-06-29 14:27 UTC
Labels: bug, needs-triage, size:M - 3, area:device

**Comment by Steve-Mcl** [comment] 2023-07-03 16:12
Verified on staging:



https://github.com/flowforge/flowforge/assets/44235289/ed834e1a-1ee1-4b00-8f12-59281b21fd31
