### ISSUE TITLE
Allow setting preinstalled modules in templates

### ISSUE THREAD

**Issue by ZJvandeWeg** [flowforge/flowforge#2002] opened 2023-04-13 13:21 UTC
### Description

As an admin I would like to pre-install certain modules or custom nodes through the template. So that a default can be set for the whole organisation.

---

> _Notes/context copied from #1339_

We added the ability to list modules in Project Settings as https://github.com/flowforge/flowforge/issues/405 / https://github.com/flowforge/flowforge/pull/1090

This is stored against the individual Project.

We didn't add them to the Project Template to keep the scope manageable given only Admin users can create Templates currently.

Before we look at allowing Teams to create their own Templates (https://github.com/flowforge/flowforge/issues/407), we should ensure the module list options are added to the Template structure and edit UX.

---
```[tasklist]
### Modules to be added as standard
- [ ] https://github.com/flowforge/flowforge/issues/1233
- [ ] https://github.com/flowforge/flowforge/issues/1234
```

## Notes 2023-06-14
Following discussion with @knolleary around pros + cons of inheriting vs coping palette modules from template to the instance, it was determined that in this iteration, to minimise complexity, palette modules should be copied from the template to the instance at the time of instance creation only. This solves a lot of questions around "what if there are 100 instances, suddenly they all get this new node? what if a user wants to remove or update an instance? what are the merge rules? etc

Based on the above, the following items are specific (additional) **done** criteria 
- [ ] palette modules are only copied from template to the instance upon creation of an instance
   - [ ] docs should include this information
- [ ] adding a module to the template does NOT suddenly add to existing instances
- [ ] can remove inherited modules & they do NOT re-appear
- [ ] modules listed actually get installed and are usable

**Comment by ZJvandeWeg** [comment] 2023-04-13 13:21
@MarianRaphael This might be a route to implement: https://github.com/flowforge/flowforge/issues/1233 ?

**Comment by knolleary** [comment] 2023-04-20 09:45
Duplicate of https://github.com/flowforge/flowforge/issues/1339 - but this one has been planned, so I'll close the existing issue for this.

**Closed** 2023-06-20 14:53 UTC
Labels: feature-request, needs-triage, size:L - 5, priority:high

**Comment by hardillb** [comment] 2023-07-03 09:51
Verified this on staging by adding the node-red-debugger
