### ISSUE TITLE
Email configuration detection error.

### ISSUE THREAD

**Issue by thebaldgeek** [flowforge/flowforge#1731] opened 2023-02-20 23:05 UTC
### Description

First time installing Flow Forge.   
Ubuntu 22.04. Local Install. Download installer, unzip, run script.   
Follow configuration guide. Setup application specific password on gmail, enable exactly as per example here:
https://flowforge.com/docs/install/email_providers/   
Visit http://localhost:3000, click start.   
Notice red warning saying email is not configured and should be before continuing.   
Stop service, double check .yml file. No errors, start service, same red warning.  
     
Email configuration is not correctly detected, following warning text suggests I don't create first admin user till rectified.   
(Inviting users to platform via email is an important feature I'd like to test/use).

Thanks.

Ben

**Comment by knolleary** [comment] 2023-02-20 23:48
Hi @thebaldgeek 

Can you check the log output when you start FlowForge for any messages regarding the email configuration?

**Comment by thebaldgeek** [comment] 2023-02-20 23:56
I'd be happy to, but after looking for a good while, cant find any logs.
Does some extra debug level have to be turned on first?

**Comment by knolleary** [comment] 2023-02-21 00:07
Does the following command find the logs?

```
journalctl -f -u FlowForge -o cat
```

I don't currently have a suitable box to hand to double check that... but either way, we need to get it documented.

**Comment by thebaldgeek** [comment] 2023-02-21 00:14
Running that command prevents Flow Forge from starting (using 'sudo service flowforge start) or stopping.
No logs or trace in the terminal.
Refreshing the browser brings up the 'start' and then the dialog to create the first user and the note about no email configured.

**Comment by knolleary** [comment] 2023-02-21 00:24
That command just dumps the log output of the already running service - it doesn't start/stop the service.

The `-o cat` option makes it keep outputing the logs 'live' rather than just dumping the most recent logs.

Are you seeing the log output when you run that command?

**Comment by thebaldgeek** [comment] 2023-02-21 00:44
Understood.
No, not seeing any log output.
![image](https://user-images.githubusercontent.com/7385116/220220297-12854781-0491-4b68-9e09-6e1a8f9b92de.png)

**Comment by knolleary** [comment] 2023-02-21 10:55
With the `journalctl` command running in one terminal, can you restart the FF service. You should then get the startup logs being reported by the `journalctl` command.

Can you also share your `flowforge.yml` file (with any credentials etc replaced) so we can see exactly how you have added the email config to the file?

**Comment by thebaldgeek** [comment] 2023-02-21 14:44
Running the jornalctl in one tab and starting Flow Forge in the other still results in no logging (I have been using the two tabs for each test thus far).    

```port: 3000
host: 0.0.0.0
domain: 10.10.10.2
base_url: http://10.10.10.2:3000
# support_contact: mailto:support@example.com

#################################################
# Database Configuration                        #
#################################################

db:
  logging: false
  ## The database type: sqlite|postgres
  type: sqlite
  
  ### SQLite options

  ## The database filename. Relative to $FLOWFORGE_HOME/var/
  ## Set to ':memory:' for a database that is wiped on restart
  storage: forge.db

  ### Postgres options

  # host: localhost
  # user: forge
  # password: secret

#################################################
# Project Driver Configuration                  #
#################################################

driver:
  ## The type of backend driver to use
  ##  Can be: localfs/docker/stub/k8s
  type: localfs

  options:
    ## Options to be passed to the driver

    ### LocalFS options

    ## The first port number to assign to projects
    # start_port: 12080

    ## Path to find node executable if not on the default path
    # node_path: /usr/bin/node

    ### Docker options

    ## Docker socket path
    # socket: /var/run/docker.sock

    ### K8S options

    ## Kubectl conf file to contact the cluster
    # config_file: /opt/share/projects/flowforge/test/config

#################################################
# MQTT Broker Configuration                     #
#################################################

# broker:
  ## Internal url used by the platform to connect to the broker
  # url: mqtt://localhost:4880
  ## External url used by devices to connect to the broker, if different
  # public_url: ws://localhost:4881


#################################################
# File Server config                            #
#################################################

fileStore:
  url: http://localhost:3001


#################################################
# Email Configuration                           #
#################################################

email:
  enabled: true
  debug: false
  smtp:
    host: smtp.googlemail.com
    port: 587
    secure: true
    auth:
      user: myemailaddress@gmail.com
      pass: appspecifcpasswd

#################################################
# Telemetry Configuration                       #
#################################################
telemetry:
  enabled: true```

**Comment by hardillb** [comment] 2023-02-21 14:55
Just a thought, as a test can you add a `from` field to the mail config

```yaml
email:
  enabled: true
  debug: false
  from: myemailaddress@gmail.com
  smtp:
    host: smtp.googlemail.com
    port: 587
    secure: true
    auth:
      user: myemailaddress@gmail.com
      pass: appspecifcpasswd
```

This may be Google refusing to send email "from" somebody other than yourself, it defaults to `"FlowForge Platform" <donotreply@flowforge.com>`

**Comment by thebaldgeek** [comment] 2023-02-21 15:14
Added a from field, using the same email address. Getting the same error.
Then put the 'from' email address to be my day-to-day address, stopped and started the service, same warning on the creation page.    
Still no logging with the `journalctl -f -u FlowForge -o cat` command


![image](https://user-images.githubusercontent.com/7385116/220383411-6c171557-2dac-442f-92b9-25bcd7ec69de.png)

**Comment by hardillb** [comment] 2023-02-21 15:17
Just to be 100% clear the email address should match the one you are using to authenticate, the one used to generate the token.

This was a bit of a long shot, but I thought it worth testing.

**Comment by thebaldgeek** [comment] 2023-02-21 15:18
Correct, I first used one I have the app password for, and when it did not work, I thought I would try my usual. ie, both options tested.

**Comment by thebaldgeek** [comment] 2023-03-09 17:10
I have now tested the email account and its application specific password in a few other apps and have no issues there.
Is there any other information I can try and gather to help? (Still not sure why there are no log files at this point).

I am going to take a copy of the VM as I really need to create the project and start working on testing Flow Forge for my aircraft application. (The red text seems to suggest that once I create the account with broken email, I am forever doomed, so hence the copy of the VM so I can go back and restart at some point with email working).

**Comment by hardillb** [comment] 2023-03-09 17:14
Setting up an account without email enabled is not a problem, the side effects are:

1. no way to do password recovery
2. no way to invite new users to join your teams, you can still create new users and add them to teams

And once we work things out, you can then enable email and those features will work.

I will see if I can reproduce this locally and see where we get.

**Comment by thebaldgeek** [comment] 2023-05-16 13:57
Am I able to provide any further testing / debugging on this issue?
I'd like to start inviting team members to the project and take advantage of the user audit features in Flow Forge.

**Comment by hardillb** [comment] 2023-05-17 07:15
Quick test, change port to 465

**Comment by thebaldgeek** [comment] 2023-05-18 13:40
Made the change, how can I enable email in Flow Forge?
Trying to invite a member via email results in an error 'email invitations not available'.

I have stopped and started the service.

**Comment by hardillb** [comment] 2023-05-18 13:42
You have to enable invites for new users under the admin settings

**Comment by hardillb** [comment] 2023-05-18 20:44
There is not enough logs there to show the message that is has successfully tested the email settings, but it looks like they are working as the settings are enabled.

As for inviting team members you have have scrolled far enough down that list of settings. 

The one you need to tick to enable the one you are trying to test is "allow users to invite external users to teams"

![Screenshot from 2023-05-18 21-41-04](https://github.com/flowforge/flowforge/assets/1800845/f256fbd0-dec8-4ab5-936a-5b5428d9f394)

**Comment by thebaldgeek** [comment] 2023-05-18 21:02
Its working!
Awesome. Thanks for the help.

Unfortunately, now that I have seen the invite process, its not really like I expected.
There is no way to provide a new member with the dashboard URL and they are logged into the Flow Forge console after accepting the invite.
There is also nothing obvious either on how to move from the Node-RED editor to dashboard if they stumble on the 'open editor' button.
Is there a way to change the email verification text or endpoint to point them to the Node-RED /ui/ URL once they verify their email?

**Comment by hardillb** [comment] 2023-05-19 10:24
The invitations is not meant to be for access to the dashboard-ui or any API hosted in Node-RED, you are inviting user to the FlowForge team to be able to access to Node-RED editor and FlowForge features.

While we do offer the ability to use FlowForge to authenticate for API/Dashboard that is just a value add on top of the FlowForge access.

No, the email text for an invite is fixed.

We do have an open feature we are looking at which is a FlowForge RBAC level that would JUST allow access to API/Dashboard, which if implemented would just allow access to  API/Dashboard endpoints, which it may make sense to provide a different email text.

I'm going to close this as the reason it was opened is fixed.

**Closed by hardillb** 2023-05-19 10:24 UTC
Labels: needs-triage
