### ISSUE TITLE
Show FlowForge Version on Admin Overview page

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#480] opened 2022-04-13 16:17 UTC
### Description

We print the running version of FlowForge at startup in the logs, but it would be useful to quickly check the running version from the web interface.

**As an** Admin
**I want to** check the running FlowForge Version
**So that I can** provide better bug reports and know if I need to upgrade

**Comment by sammachin** [comment] 2022-04-14 08:26
- We should also include information such as NodeJS version, and NPM version, 
- We should include versions of all the FlowForge packages installed.
- This information should be in a format such that it can easily be copy/pastes into an issue when raising a bug.

Does this need a new API endpoint to provide the information or is it already available to the front end?

**Comment by hardillb** [comment] 2022-04-14 08:35
The app currently logs the following at startup

```
[2022-04-14T08:30:41.406Z] INFO: FlowForge v0.3.0
[2022-04-14T08:30:41.408Z] INFO: FlowForge running with NodeJS v16.14.1
[2022-04-14T08:30:41.408Z] INFO: FlowForge Data Directory: /opt/share/projects/flowforge/flowforge
[2022-04-14T08:30:41.409Z] INFO: Config File: /opt/share/projects/flowforge/flowforge/etc/flowforge.local.yml
[2022-04-14T08:30:41.417Z] INFO: Database driver: sqlite
[2022-04-14T08:30:41.417Z] INFO: Database file: /opt/share/projects/flowforge/flowforge/var/forge.db
```
But this isn't available to the Web Front end currently, it would require a new endpoint

**Comment by sammachin** [comment] 2022-06-27 13:55
duplicate of #655

**Closed by sammachin** 2022-06-27 13:55 UTC
Labels: story, Enterprise

**Comment by hardillb** [comment] 2022-06-28 08:14
As this is a duplicate should it be removed from the development board (it's added an extra "No Status" comment)

**Comment by sammachin** [comment] 2022-06-28 08:17
yup, not quite sure how it got added to the dev board, some automation somewhere going a bit strange
